services:
  civic-action-app:
    container_name: civic-action-app
    image: masterboxer/civic-action-app:1.0.0
    build:
      context: .
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    command: air
    environment:
      DATABASE_URL: "host=civic_action_db user=postgres password=postgres dbname=pulse sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - civic_action_db
    networks:
      - pulse-net

  civic_action_db:
    container_name: civic_action_db
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pulse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pulse-net

volumes:
  pgdata: {}
  go-mod-cache: {}

networks:
  pulse-net:
