services:
  micro-journal-app:
    image: masterboxer/micro-journal-app:1.0.0
    build:
      context: .
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    command: air
    environment:
      DATABASE_URL: postgres://postgres:postgres@micro_journal_db:5432/journal?sslmode=disable

    ports:
      - "8200:8200"
    depends_on:
      - micro_journal_db
    networks:
      - journal-net

  micro_journal_db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: journal
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - journal-net

volumes:
  pgdata: {}
  go-mod-cache: {}

networks:
  journal-net:
